// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlaIsc25xBv3CSD5FG-aShePIIX-frY44',
    appId: '1:924050355138:web:7ee3b351b30e9fc9161c5b',
    messagingSenderId: '924050355138',
    projectId: 'kia-cerdas',
    authDomain: 'kia-cerdas.firebaseapp.com',
    storageBucket: 'kia-cerdas.firebasestorage.app',
    measurementId: 'G-GDTCYVPQHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfCrkjVRSDYLTYJFcne64aSjYWIo3Of28',
    appId: '1:924050355138:android:ea5fc2d7bded9e48161c5b',
    messagingSenderId: '924050355138',
    projectId: 'kia-cerdas',
    storageBucket: 'kia-cerdas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoaCzXncKgbmu-ll3DH2PDe2qXA8egHcg',
    appId: '1:924050355138:ios:79b98040746223ab161c5b',
    messagingSenderId: '924050355138',
    projectId: 'kia-cerdas',
    storageBucket: 'kia-cerdas.firebasestorage.app',
    iosBundleId: 'com.example.taPa2Pa3Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoaCzXncKgbmu-ll3DH2PDe2qXA8egHcg',
    appId: '1:924050355138:ios:79b98040746223ab161c5b',
    messagingSenderId: '924050355138',
    projectId: 'kia-cerdas',
    storageBucket: 'kia-cerdas.firebasestorage.app',
    iosBundleId: 'com.example.taPa2Pa3Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlaIsc25xBv3CSD5FG-aShePIIX-frY44',
    appId: '1:924050355138:web:594f36090b29b1a8161c5b',
    messagingSenderId: '924050355138',
    projectId: 'kia-cerdas',
    authDomain: 'kia-cerdas.firebaseapp.com',
    storageBucket: 'kia-cerdas.firebasestorage.app',
    measurementId: 'G-3M32QX6KVT',
  );
}
